 * Debugger is active!
 * Debugger PIN: 992-358-344
65.87.19.170 - - [19/Jun/2017 06:46:51] "GET / HTTP/1.1" 200 -
65.87.19.170 - - [19/Jun/2017 06:47:01] "GET /video-violence-detection HTTP/1.1" 200 -
65.87.19.170 - - [19/Jun/2017 06:47:01] "GET /video-violence-detection HTTP/1.1" 200 -
65.87.19.170 - - [19/Jun/2017 06:47:08] "GET /video-violence-detection-detail?videoName=football_crowds_cheering__Kickoff_in_Camp_Randall__spt414__bEZahnaRpmQ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/webapp/sedaweb/gsuWebApp/gsuVideoViolenceDetection.py", line 78, in vvd_detail
    Npredictions.append(model.predict(x))
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1569, in predict
    self._make_predict_function()
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1037, in _make_predict_function
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2095, in function
    return Function(inputs, outputs, updates=updates)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2049, in __init__
    with tf.control_dependencies(self.outputs):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3651, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3382, in control_dependencies
    c = self.as_graph_element(c)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2473, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2552, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("dense_2/Softmax:0", shape=(?, 2), dtype=float32) is not an element of this graph.
65.87.19.170 - - [19/Jun/2017 06:47:08] "GET /video-violence-detection-detail?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
65.87.19.170 - - [19/Jun/2017 06:47:08] "GET /video-violence-detection-detail?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
65.87.19.170 - - [19/Jun/2017 06:47:08] "GET /video-violence-detection-detail?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
65.87.19.170 - - [19/Jun/2017 06:47:09] "GET /video-violence-detection-detail?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
65.87.19.170 - - [19/Jun/2017 06:47:09] "GET /video-violence-detection-detail?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
^C
